#helm:generate helmc tpl -d tpl/values.toml -o manifests/rabbitmq-rc.yaml $HELM_GENERATE_FILE
apiVersion: v1
kind: ReplicationController
metadata:
  name: rabbitmq
  labels:
    provider: rabbitmq
    heritage: bitnami
spec:
  replicas: 1
  selector:
    provider: rabbitmq
    version: 3.6.2-r0
  template:
    metadata:
      labels:
        provider: rabbitmq
        version: 3.6.2-r0
        heritage: bitnami
    spec:
      containers:
      - name: rabbitmq
        image: bitnami/rabbitmq:3.6.2-r0
        env:
        - name: RABBITMQ_USERNAME
          value: {{ .rabbitmqUsername | quote }}
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq
              key: rabbitmq-password
        - name: RABBITMQ_ERLANGCOOKIE
          valueFrom:
            secretKeyRef:
              name: rabbitmq
              key: rabbitmq-erlangcookie
        - name: RABBITMQ_NODEPORT
          value: {{ .rabbitmqNodeport | quote }}
        - name: RABBITMQ_NODETYPE
          value: {{ .rabbitmqNodetype | quote }}
        - name: RABBITMQ_NODENAME
          value: {{ .rabbitmqNodename | quote }}
        - name: RABBITMQ_CLUSTERNODENAME
          value: {{ .rabbitmqClusternodename | quote }}
        - name: RABBITMQ_VHOST
          value: {{ .rabbitmqVhost | quote }}
        - name: RABBITMQ_MANAGERBINDIP
          value: {{ .rabbitmqManagerbindip | quote }}
        ports:
        - name: rabbitmq
          containerPort: 15672
        livenessProbe:
          exec:
            command:
            - rabbitmqctl
            - status
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - rabbitmqctl
            - status
          initialDelaySeconds: 5
          timeoutSeconds: 1
        volumeMounts:
        - name: rabbitmq-data
          mountPath: /bitnami/rabbitmq
      volumes:
      - name: rabbitmq-data
        emptyDir: {}
