rabbitmqUsername = "guest"
rabbitmqPassword = "guest"
rabbitmqErlangcookie = ""
rabbitmqNodeport = "5672"
rabbitmqNodetype = "stats"
rabbitmqNodename = "rabbit-nn"
rabbitmqClusternodename = "rabbit-cnn"
rabbitmqVhost = "/"
rabbitmqManagerbindip = "0.0.0.0"
