#helm:generate helmc tpl -d tpl/values.toml -o manifests/rabbitmq-secrets.yaml $HELM_GENERATE_FILE
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq
  labels:
    provider: rabbitmq
    heritage: bitnami
type: Opaque
data:
  rabbitmq-password: "ME1ncHQ2eHB1eE5zejFRajh3aHVBWVFDNF9fOEZPT24="
  rabbitmq-erlangcookie: ""
