#helm:generate helmc tpl -d tpl/values.toml -o manifests/postgresql-secrets.yaml $HELM_GENERATE_FILE
apiVersion: v1
kind: Secret
metadata:
  name: postgresql
  labels:
    provider: postgresql
    heritage: bitnami
type: Opaque
data:
  postgres-password: {{ .postgresPassword | b64enc | quote }}
