apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    provider: postgresql
    heritage: bitnami
spec:
  ports:
  - name: postgresql
    port: 5432
    targetPort: postgresql
  selector:
    provider: postgresql
